### ISSUE TITLE
Doesn't it work in Unity 2021?

### ISSUE THREAD

**Issue by dev-shinyu** [hadashiA/VitalRouter#63]
Hello . @hadashiA 

VitalRouter I found out that this pub/sub library is also zero-allocation and has excellent performance, so I wanted to try it, but it seems that you support Unity 2022 from now on. Is it difficult to use 2021? Because I'm making a 2D game, but if you search, you can see that 2022 has 2D performance issues, so I'm still using Unity 2021. In addition, is UniTaskPubSub and UniRx MessageBroken that you made before this library completely the same? I'm wondering if UniTaskPubSub is any better than MessageBroken in terms of memory and performance. For example, if it supports zero-allocation, performance is important, but memory efficiency should be good, so I'm wondering if UniTaskPubSub has any improvements over MessageBroken. And I'm also wondering how much difference in performance and memory efficiency there is if you just use the basic features of pub/sub compared to VitalRouter.

Thank you :)

.VitalRouterさん、こんにちは。このpub/subライブラリもゼロアロケーションでパフォーマンスが優れていることがわかったので、試してみたかったのですが、今後はUnity2022をサポートするようですね。2021を使うのは難しいのでしょうか？というのも、2Dのゲームを作っているのですが、検索すると2022は2Dのパフォーマンスに問題があるようなので、まだUnity2021を使っています。なお、このライブラリの前に作ったUniTaskPubSubとUniRx MessageBrokenは完全に同じものですか？UniTaskPubSubの方がMessageBrokenよりもメモリやパフォーマンスの面で優れているのか気になります。例えば、ゼロ・アロケーションに対応しているのであれば、パフォーマンスも重要ですが、メモリ効率も良いはずなので、UniTaskPubSubはMessageBrokenよりも改善されているのか気になります。また、Pub/Subの基本的な機能だけを使った場合、VitalRouterと比べてパフォーマンスやメモリ効率にどの程度の差があるのかも気になります。

**Comment by hadashiA** [comment]
@dev-shinyu  Hello. Sorry for the late reply. I couldn't keep an eye on the issue.

Regarding your question, I don't think we will support 2021.
The main reason is because of the SouceGenerator feature.
Besides, 2021 is a bit too old. I am sure the newer version will perform better.

Regarding the difference with UniTaskPubSub. I think VitalRouter probably performs better. It uses code generation and takes care of Subscription handling. I don't have any measured results, though; UniRx.MessageBroker is an even older implementation, so the later one should be an improvement.
